# Generated by Django 5.1.3 on 2024-11-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransasctionsModel',
            new_name='TransactionsModel',
        ),
    ]
